modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
mixins = ["extendedae_plus.mixins.json"]

[[mods]]
modId = "${mod_id}"
displayURL="https://github.com/GaLicn/ExtendedAE_Plus"
issueTrackerURL = "https://github.com/GaLicn/ExtendedAE_Plus/issues"
version = "${mod_version}"
displayName = "${mod_name}"
credits = "C-H716 for Code Contribution"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "extendedae_plus.png"

[[dependencies.extendedae_plus]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedae_plus]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedae_plus]]
modId = "expatternprovider"
mandatory = true
versionRange = "[1.20-1.4.6-forge,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.extendedae_plus]]
modId = "mae2"
mandatory = false
versionRange = "[2.0.0-alpha,)"
ordering = "NONE"
side = "BOTH"
